run_mode: test

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../data/train_joint.npy
  label_path: ../data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: ../data/val_joint.npy
  label_path: ../data/val_label.npy
  split: test
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: True

# model
model: model.sttformer.Model
model_args:
  len_parts: 6
  num_frames: 120
  num_joints: 17
  num_classes: 155
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 3
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16],
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64],
           [256, 256, 64], [256, 256, 64]]

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: [0]
cuda_visible_device: '0,1,2,3'
batch_size: 32
test_batch_size: 32
num_epoch: 90
nesterov: True
