# command line: main.py --phase test --save-score true --config config/val/tegcn_jb.yaml

base_lr: 0.01
batch_size: 256
config: config/val/tegcn_jb.yaml
device: 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.tegcn.Model
model_args:
  graph: graph.uav_te.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: false
num_epoch: 80
num_worker: 32
optimizer: SGD
phase: test
print_log: true
save_epoch: 30
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 128
test_feeder_args:
  data_path: ../data/val_joint_bone.npy
  debug: false
  label_path: ../data/val_label.npy
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: work_dir/best/tegcn_jb/te_g-41-10962.pt
work_dir: ../ensemble_results/tegcn/val/tegcn_jb
